### ISSUE TITLE
@bem-react/core: Compose not supported defaultProps

### ISSUE THREAD

**Issue by yarastqt** [bem/bem-react#340]
```tsx
interface FooProps {
  bar: string
}

class FooBase extends PureComponent<FooProps> {
  static defaultProps = { bar: 'value' }
}

const Foo = compose(...)(FooBase)
const App = () => <Foo /> // bar is required
```

**Comment by awinogradov** [comment]
So, it's not a bug in `core`. When you use a `compose` you make the new Component, which can have a different `defaultProps`. Also, in fact, this problem doesn't connect to `compose`. It's connected to the HOCs. Now I think it's correct behavior, because of a component before composition and after are different components.

**Comment by awinogradov** [comment]
Relevant issue https://github.com/Microsoft/TypeScript/issues/23812

**Comment by yarastqt** [comment]
Need use `JSX.LibraryManagedAttributes` for result props from compose :)
