### ISSUE TITLE
@bem-react/classname: Create element cnGenerators with block cnGenerators

### ISSUE THREAD

**Issue by isqua** [bem/bem-react#406]
I have an element with some elements, which may have some mixes and modifiers. And I have to create component functions with passing block name again:

```jsx
const cnPopup = cn('Popup')
const cnPopupClose = cn('Popup', 'Close')
const cnPopupContent = cn('Popup', 'Content')

<div className={cnPopup({ theme: 'white' }, [mixPopup])}>
  <button className={cnPopupClose({ theme: 'dark' })}>close</button>
  <div className={cnPopupContent(null, [mixContent])}>
    some text
  </div>
</div>
```

But want something like this:

```jsx
const cnPopup = cn('Popup') // Creating not only cnGenerator, but a namespace
const cnPopupClose = cnPopup('Close') // which can be used for creating other cnGenerators
const cnPopupContent = cnPopup('Content')

<div className={cnPopup({ theme: 'white' }, [mixPopup])}> // and still for creating class lists
  <button className={cnPopupClose({ theme: 'dark' })}>close</button>
  <div className={cnPopupContent(null, [mixContent])}>
    some text
  </div>
</div>
```

What do you think about it?

**Comment by awinogradov** [comment]
Hi, @isqua. We tried to make your proposal in the beginning of classname package. But if you don't need modifiers your code will be look like that

``` jsx
<div className={cnPopup({ theme: 'white' }, [mixPopup])}> // and still for creating class lists
  <button className={cnPopupClose()}>close</button>
  <div className={cnPopupContent()}>
    some text
  </div>
</div>
```

Or if you share cnPopup between elements

``` jsx
import { cnPopup } from '../';

<div className={cnPopup('Wrapper')()}> // and still for creating class lists
  <button className={cnPopup('Close')()}>close</button>
  <div className={cnPopup('Content')()}>
    some text
  </div>
</div>
```

One more problem with carrying is unsupported valueOf method in TypeScript. In JS you can write `<button className={cnPopup('Close')}>close</button>` without last call, because we can override toString and valueOf method, but in React and TypeScript it doesn't matter. className prop must be string, but in this case it's function. TypeScript call you to write this `<button className={cnPopup('Close').toString()}>close</button>`.

**Comment by isqua** [comment]
> But if you don't need modifiers your code will be look like that
> 
> ```jsx
> <div className={cnPopup({ theme: 'white' }, [mixPopup])}>
>   <button className={cnPopupClose()}>close</button>
>   <div className={cnPopupContent()}>
>     some text
>   </div>
> </div>
> ```

my code is actually looks like that, because block class names (stirngs i mean) is still generated with parentheses :)

> Or if you share `cnPopup` between elements
> 
> ```jsx
> import { cnPopup } from '../';
> 
> <div className={cnPopup('Wrapper')()}>
>  <button className={cnPopup('Close')()}>close</button>
>  <div className={cnPopup('Content')()}>
>    some text
>  </div>
> </div>
> ```

Why do you think it is a problem for elements, but ok for blocks?
